### PR TITLE
Add support of numpy inputs to covariance_transformers

### PR DESCRIPTION
**Pull request by apmellot**
An error was raised in _check_data when X is a numpy input because it was testing `X.values.dtype == 'object'`.

### CODE REVIEW

**Review by dengemann — APPROVED** [review]

**Comment by agramfort** [comment]
@apmellot can you please add/update a unit test to validate this change?

and we need to fix the deprecation of PSD to have this PR green. See https://github.com/coffeine-labs/coffeine/issues/36

**Comment by dengemann** [comment]
This can now be updated as we merged #39 :)

**Comment by antoinecollas** [comment]
Will this PR be merged soonish or is there something missing?

**Comment by dengemann** [comment]
Someone needs to rebase it and tests need to pass. Volunteers welcomed :)

**Review by agramfort — APPROVED** [review]

**Comment by agramfort** [comment]
thx @apmellot

**Pull request merged**
