### PR TITLE
Changing default Riemann projection scale to `auto`

### PR DESCRIPTION
**Pull request by hubertjb**
@dengemann if I remember correctly the default scale for Riemann projection had to be changed from 1 to 'auto'.

### CODE REVIEW

**Comment by dengemann** [comment]
not sure we finished discussing this topic. there is still something to understand as this rescaling shouldn't be necessary, in principle.

**Comment by agramfort** [comment]
what is the scale parameter doing?

**Comment by dengemann** [comment]
remember it normalises covariances by trace (total power)

**Comment by dengemann** [comment]
Thanks a lot @agramfort you make my day. Any HTML output to share?

**Pull request merged**
