### PR TITLE
attempt to fix... does not work yet

### PR DESCRIPTION
**Pull request by agramfort**
it's more tricky than expected...

cc @apmellot 

@dengemann pb arises when you have only one sample in X

### CODE REVIEW

**Comment by dengemann** [comment]
I think I have dealt with something related but not exactly the same. @apmellot can you tell when this corner case occurs? Could be interesting. Unless you do a leave one out cross-validation (or testing) this should never happen right?

**Comment by apmellot** [comment]
It indeed occurs when I am doing some tests and only using 10 subjects in the 10-fold cross validation.

**Comment by agramfort** [comment]
can you share a test code snippet?

>

**Comment by apmellot** [comment]
`import numpy as np
import pandas as pd
from meegpowreg.spatial_filters import ProjCommonSpace

n_compo = 'full'
scale = 'auto'
reg = 0

freq_bands = {'alpha': (8.0, 15.0)}
n_freq_bands = len(freq_bands)
n_subjects = 1
n_channels = 4

X_cov = np.random.randn(n_freq_bands, n_subjects, n_channels, n_channels)
X_df = pd.DataFrame(
  {band: list(X_cov[:, ii]) for ii, band in enumerate(freq_bands)})

riemann = ProjCommonSpace(scale=scale, n_compo=n_compo, reg=reg)
riemann.transform(X_df)`

**Comment by dengemann** [comment]
Not sure wha this was trying to fix. Closing for now.

**Pull request closed without merging**
